export const EXPENSE_CATEGORIES = [
  "Cost of Goods Sold (Stock/Materials)",
  "Inventory Write-off (Stock Obsolescence)",
  "Fuel & Diesel (Generator/Vehicle)",
  "Rent & Service Charge",
  "Salaries & Wages",
  "Directors' Remuneration",
  "Pension Contributions",
  "Statutory Contributions (ITF/NSITF/NHIS)",
  "Redundancy & Severance Pay",
  "Medical & Health Expenses",
  "Staff Welfare & Entertainment",
  "Security & Cleaning",
  "Utilities (Power/Water)",
  "Internet & Communication",
  "Professional Services",
  "Management & Technical Fees",
  "AGM & Statutory Meetings",
  "Licenses & Permits",
  "Subscriptions & Dues",
  "Marketing & Advertising",
  "Repairs & Maintenance",
  "Travel & Transport",
  "Foreign Travel & Hotels",
  "Office Supplies",
  "Insurance",
  "Bank Charges & Interest",
  "Realized FX Loss",
  "Digital Asset Loss (Crypto/Tokens)",
  "Pre-Operational Expenses (Startup)",
  "Training & Development",
  "Research & Development",
  "Donations (Appr. Bodies)",
  "Environmental & Waste Management",
  "Bad Debts",
  "General Business Expense (Wholly & Exclusively)",
] as const;

export type ExpenseCategory = typeof EXPENSE_CATEGORIES[number];
