/**
 * Client-Safe Subscription Pricing Constants
 * 
 * This file contains subscription pricing data that can be safely imported
 * in client components without pulling in server-side dependencies (MongoDB, etc.)
 * 
 * IMPORTANT: Keep this in sync with src/lib/server/subscription/service.ts
 * The SUBSCRIPTION_PRICING constant should match exactly.
 */

import { SubscriptionPlan } from "@/lib/server/utils/enum";

export const SUBSCRIPTION_PRICING = {
  [SubscriptionPlan.Free]: {
    monthly: 0,
    yearly: 0,
      features: {
      invoicesPerMonth: 5,
      vatTracking: true,
      whtTracking: false,
      payroll: false,
      exports: false,
      watermark: true,
      expenseTracking: true,
      expensesPerMonth: 30,
      realTimeTaxCalculation: true,
      monthlyProfitTracking: true,
      individualAccounts: true,
      multipleAccounts: false,
      maxCompanies: 1,
      maxBusinesses: 1,
      pitTracking: true,
      pitReturns: false,
      pitRemittance: false,
      incomeSources: 3,
      citTracking: true,
      citRemittance: false,
      vatRemittance: false,
      multipleCompanies: false,
      whiteLabel: false,
      allFeatures: false,
      allPages: false,
      advancedReporting: false,
      expenseCategories: 5,
    },
  },
  [SubscriptionPlan.Starter]: {
    monthly: 3500,
    yearly: 35000,
    features: {
      invoicesPerMonth: -1,
      vatTracking: true,
      whtTracking: true,
      payroll: false,
      exports: true,
      watermark: false,
      expenseTracking: true,
      expensesPerMonth: 500,
      realTimeTaxCalculation: true,
      monthlyProfitTracking: true,
      individualAccounts: true,
      multipleAccounts: false,
      maxCompanies: 1,
      maxBusinesses: 1,
      pitTracking: true,
      pitReturns: true,
      pitRemittance: true,
      incomeSources: 10,
      citTracking: true,
      citRemittance: true,
      vatRemittance: true,
      multipleCompanies: false,
      whiteLabel: false,
      allFeatures: false,
      allPages: false,
      advancedReporting: false,
      expenseCategories: 20,
    },
  },
  [SubscriptionPlan.Standard]: {
    monthly: 8500,
    yearly: 85000,
    features: {
      invoicesPerMonth: -1,
      vatTracking: true,
      whtTracking: true,
      payroll: true,
      exports: true,
      watermark: false,
      expenseTracking: true,
      expensesPerMonth: -1,
      realTimeTaxCalculation: true,
      monthlyProfitTracking: true,
      individualAccounts: true,
      multipleAccounts: true,
      maxCompanies: 3,
      maxBusinesses: 3,
      pitTracking: true,
      pitReturns: true,
      pitRemittance: true,
      incomeSources: -1,
      citTracking: true,
      citRemittance: true,
      vatRemittance: true,
      multipleCompanies: true,
      whiteLabel: false,
      allFeatures: false,
      allPages: false,
      advancedReporting: false,
      expenseCategories: 50,
    },
  },
  [SubscriptionPlan.Premium]: {
    monthly: 25000,
    yearly: 250000,
    features: {
      invoicesPerMonth: -1,
      vatTracking: true,
      whtTracking: true,
      payroll: true,
      exports: true,
      watermark: false,
      multipleCompanies: true,
      whiteLabel: false,
      allFeatures: true,
      allPages: true,
      expenseTracking: true,
      expensesPerMonth: -1,
      realTimeTaxCalculation: true,
      monthlyProfitTracking: true,
      individualAccounts: true,
      multipleAccounts: true,
      maxCompanies: -1,
      maxBusinesses: -1,
      advancedReporting: false,
      expenseCategories: -1,
      pitTracking: true,
      pitReturns: true,
      pitRemittance: true,
      incomeSources: -1,
      citTracking: true,
      citRemittance: true,
      vatRemittance: true,
    },
  },
} as const;


