/**
 * Tax Filing Document PDF Generator
 * 
 * Generates NRS (Nigeria Revenue Service)-compliant tax filing support documents (PDFs) for download.
 * 
 * IMPORTANT DISCLAIMER:
 * - These are TAX COMPUTATION & FILING SUPPORT DOCUMENTS
 * - This application is a tax-compliance support tool, NOT a tax authority or tax agent
 * - Documents are NOT automatically submitted to NRS (Nigeria Revenue Service), State IRS, or CAC
 * - Users must manually file these documents with the appropriate tax authority
 * - All documents are clearly labeled as support documents
 * 
 * CRITICAL: This application only supports tax laws valid from 2026 onward per Nigeria Tax Act 2025.
 * NRS was rebranded to NRS (Nigeria Revenue Service) effective January 1, 2026.
 * 
 * Reference: https://www.nrs.gov.ng/
 */

import jsPDF from "jspdf";
import { Types } from "mongoose";
import Company from "../company/entity";
import Business from "../business/entity";
import { Payroll } from "../payroll/entity";
import { whtService } from "../wht/service";
import { RemittanceStatus, FilingStatus, TaxClassification, AccountType, InvoiceStatus, TransactionType } from "../utils/enum";
import { NRS_CIT_RATE } from "../../constants/nrs-constants";
import { calculateDevelopmentLevy } from "../tax/calculator";
import { logger } from "../utils/logger";

// Color palette for professional documents
const COLORS = {
  primary: [16, 185, 129], // emerald-500
  primaryDark: [5, 150, 105], // emerald-600
  text: [15, 23, 42], // slate-900
  textLight: [100, 116, 139], // slate-500
  border: [226, 232, 240], // slate-200
  warning: [245, 158, 11], // amber-500
};

/**
 * Formats currency in Nigerian Naira format
 * Uses "NGN" prefix instead of ₦ symbol for better PDF compatibility
 * CRITICAL: Preserves negative sign for losses/negative values
 */
function formatCurrency(amount: number): string {
  const isNegative = amount < 0;
  const absoluteAmount = Math.abs(amount);
  const parts = absoluteAmount.toFixed(2).split(".");
  const integerPart = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  const formatted = `${integerPart}.${parts[1]}`;
  const cleaned = formatted.replace(/[\u200B-\u200D\uFEFF\u00AD\u2000-\u200F\u2028-\u202F\u205F-\u206F]/g, "");
  const sign = isNegative ? "-" : "";
  return `${sign}NGN ${cleaned}`;
}

/**
 * Formats date in DD/MM/YYYY format
 */
function formatDate(date: Date | string): string {
  const d = typeof date === "string" ? new Date(date) : date;
  return d.toLocaleDateString("en-NG", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });
}

/**
 * Gets human-readable label for TaxClassification enum
 */
function getTaxClassificationLabel(classification: TaxClassification): string {
  switch (classification) {
    case TaxClassification.SmallCompany:
      return "Small Company";
    case TaxClassification.Medium:
      return "Large Company";
    case TaxClassification.Large:
      return "Large Company";
    default:
      return String(classification);
  }
}

/**
 * Gets month name from number (1-12)
 */
function getMonthName(month: number): string {
  const months = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
  ];
  return months[month - 1] || "";
}


/**
 * Adds a watermark to the PDF page
 */
function addWatermark(doc: jsPDF, pageWidth: number, pageHeight: number, text: string = "taxcomply.ng"): void {
  doc.saveGraphicsState();
  doc.setGState(new (doc as any).GState({ opacity: 0.1 }));
  doc.setFontSize(60);
  doc.setTextColor(150, 150, 150);
  doc.setFont("helvetica", "bold");
  
  // Rotate text 45 degrees around center
  const angle = 45;
  const rads = angle * (Math.PI / 180);
  const cx = pageWidth / 2;
  const cy = pageHeight / 2;
  
  doc.text(text, cx, cy, { 
    align: "center", 
    baseline: "middle", 
    angle: 45 
  });
  
  doc.restoreGraphicsState();
}

/**
 * Adds standard disclaimer footer to all tax filing documents
 */
function addDisclaimerFooter(doc: jsPDF, pageWidth: number, pageHeight: number): void {
  // Calculate available space - start footer higher to prevent overflow
  const footerMaxWidth = pageWidth - 40;
  const lineHeight = 3.5;
  // Start footer higher to ensure all text fits (5 lines * 3.5 = 17.5mm, plus 5mm margin = 22.5mm)
  const footerStartY = pageHeight - 22;
  
  doc.setFontSize(7);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
  
  const disclaimer = [
    "This is a Tax Computation & Filing Support Document generated by taxcomply.com.ng.",
    "TaxComply NG is a tax-compliance support application, NOT a tax authority or tax agent.",
    "This document is NOT automatically submitted to NRS (Nigeria Revenue Service), State IRS, or CAC.",
    "You must manually file this document with the appropriate tax authority.",
    "For official filing requirements, visit: https://www.nrs.gov.ng/",
  ];
  
  let yPos = footerStartY;
  for (const line of disclaimer) {
    // Split long lines to prevent overflow and ensure proper wrapping
    const wrappedLines = doc.splitTextToSize(line, footerMaxWidth);
    for (const wrappedLine of wrappedLines) {
      // Safety check - ensure we don't go beyond page boundary
      if (yPos >= pageHeight - 3) {
        break;
      }
      doc.text(wrappedLine, pageWidth / 2, yPos, { align: "center" });
      yPos += lineHeight;
    }
  }
}

/**
 * Adds document header with company info and document type
 */
function addDocumentHeader(
  doc: jsPDF,
  pageWidth: number,
  company: any,
  documentTitle: string,
  period: string
): number {
  let yPos = 20;
  const margin = 20;
  
  // Document Title
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.primaryDark[0], COLORS.primaryDark[1], COLORS.primaryDark[2]);
  doc.text(documentTitle, pageWidth / 2, yPos, { align: "center" });
  yPos += 8;
  
  // Subtitle - Support Document Label
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
  doc.text("Tax Computation & Filing Support Document", pageWidth / 2, yPos, { align: "center" });
  yPos += 10;
  
  // Period
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  doc.text(`Period: ${period}`, pageWidth / 2, yPos, { align: "center" });
  yPos += 15;
  
  // Company Information Section
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Taxpayer Information", margin, yPos);
  yPos += 6;
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`Company Name: ${company.name}`, margin, yPos);
  yPos += 5;
  
  if (company.tin) {
    doc.text(`Tax Identification Number (TIN): ${company.tin}`, margin, yPos);
    yPos += 5;
  }
  
  if (company.cacNumber) {
    doc.text(`CAC Registration Number: ${company.cacNumber}`, margin, yPos);
    yPos += 5;
  }
  
  if (company.address) {
    doc.text(`Address: ${company.address}`, margin, yPos);
    yPos += 5;
  }
  
  if (company.city && company.state) {
    doc.text(`City/State: ${company.city}, ${company.state}`, margin, yPos);
    yPos += 5;
  }
  
  if (company.phoneNumber) {
    doc.text(`Phone: ${company.phoneNumber}`, margin, yPos);
    yPos += 5;
  }
  
  if (company.email) {
    doc.text(`Email: ${company.email}`, margin, yPos);
    yPos += 5;
  }
  
  yPos += 5;
  
  // Generation date
  doc.setFontSize(8);
  doc.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
  doc.text(`Generated on: ${formatDate(new Date())}`, pageWidth - margin, yPos, { align: "right" });
  yPos += 10;
  
  // Draw separator line
  doc.setDrawColor(COLORS.border[0], COLORS.border[1], COLORS.border[2]);
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;
  
  return yPos;
}

/**
 * Generates VAT Return Filing Support Document (Monthly)
 * Reference: NRS (Nigeria Revenue Service) VAT Return Form Structure
 * 
 * CRITICAL: This application only supports tax laws valid from 2026 onward per Nigeria Tax Act 2025.
 * NRS was rebranded to NRS (Nigeria Revenue Service) effective January 1, 2026.
 */
export async function generateVATReturnPDF(
  entityId: Types.ObjectId,
  month: number,
  year: number,
  accountType: AccountType,
  isWatermarked: boolean = false
): Promise<Buffer> {
  // CRITICAL: Validate accountType
  if (!accountType || (accountType !== AccountType.Company && accountType !== AccountType.Business)) {
    throw new Error(`CRITICAL: accountType is required and must be AccountType.Company or AccountType.Business. Received: ${accountType || "undefined"}`);
  }

  // Get entity (Company or Business) for document header
  let entity: any;
  let entityForHeader: any;
  if (accountType === AccountType.Company) {
    entity = await Company.findById(entityId);
    if (!entity) {
      throw new Error("Company not found");
    }
    // Company structure matches addDocumentHeader expectations
    entityForHeader = entity;
  } else {
    entity = await Business.findById(entityId);
    if (!entity) {
      throw new Error("Business not found");
    }
    // Map Business structure to match addDocumentHeader expectations
    entityForHeader = {
      name: entity.name,
      tin: entity.tin || "",
      cacNumber: entity.businessRegistrationNumber || "", // Map businessRegistrationNumber to cacNumber for header
      address: entity.address || "",
      city: entity.city || "",
      state: entity.state || "",
      phoneNumber: entity.phoneNumber || "",
      email: entity.email || "",
    };
  }

  const vatService = (await import("../vat/service")).vatService;
  // CRITICAL: Use updateVATSummary to ensure fresh data for PDF generation
  // getVATSummary may return cached/stale data, but PDFs must show current accurate values
  // CRITICAL: Use entityId (not companyId) - supports both Company and Business
  const vatSummary = await vatService.updateVATSummary(entityId, month, year, accountType);
  
  if (!vatSummary) {
    throw new Error("VAT summary not found for the specified period");
  }

  // Get detailed VAT records for the period (generated on-the-fly from invoices/expenses)
  // CRITICAL: Use entityId (not companyId) - supports both Company and Business
  const vatRecordsResult = await vatService.getVATRecords(
    entityId,
    accountType,
    { month, year }
  );
  const vatRecords = vatRecordsResult.records.sort((a, b) => {
    const dateA = a.transactionDate ? new Date(a.transactionDate).getTime() : 0;
    const dateB = b.transactionDate ? new Date(b.transactionDate).getTime() : 0;
    return dateA - dateB;
  });

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;

  const period = `${getMonthName(month)} ${year}`;
  // entityForHeader is already formatted correctly (Company structure or Business mapped to Company structure)
  let yPos = addDocumentHeader(doc, pageWidth, entityForHeader, "VAT RETURN", period);

  // VAT Summary Section
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  doc.text("VAT Computation Summary", margin, yPos);
  yPos += 8;

  // VAT Summary Table
  const tableStartY = yPos;
  const colWidths = [100, 60];
  const colXPositions = [margin, pageWidth - margin - 60];

  // Table Header
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 8, "S");
  doc.text("Description", margin + 5, yPos);
  doc.text("Amount (NGN)", colXPositions[1], yPos);
  yPos += 8;

  // Table Rows
  // CRITICAL: Add null safety checks for all summary values
  const outputVAT = vatSummary.outputVAT || 0;
  const inputVAT = vatSummary.inputVAT || 0;
  const netVAT = vatSummary.netVAT || 0;
  
  doc.setFont("helvetica", "normal");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Output VAT (VAT on Sales)", margin + 5, yPos);
  doc.text(formatCurrency(outputVAT), colXPositions[1], yPos);
  yPos += 6;

  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Input VAT (VAT on Purchases)", margin + 5, yPos);
  doc.text(formatCurrency(inputVAT), colXPositions[1], yPos);
  yPos += 6;

  doc.setFont("helvetica", "bold");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Net VAT Payable/Refundable", margin + 5, yPos);
  doc.setTextColor(
    netVAT >= 0 ? COLORS.primaryDark[0] : COLORS.warning[0],
    netVAT >= 0 ? COLORS.primaryDark[1] : COLORS.warning[1],
    netVAT >= 0 ? COLORS.primaryDark[2] : COLORS.warning[2]
  );
  doc.text(formatCurrency(netVAT), colXPositions[1], yPos);
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  yPos += 8;

  // Status
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const statusText = vatSummary.status === "payable" 
    ? "VAT Payable to NRS (Nigeria Revenue Service)" 
    : vatSummary.status === "refundable"
    ? "VAT Refundable from NRS (Nigeria Revenue Service)"
    : "No VAT Payable/Refundable";
  doc.text(`Status: ${statusText}`, margin, yPos);
  yPos += 10;

  // WHT Remittance Note (WHT is separate from VAT but relevant for compliance)
  // CRITICAL: Use updateWHTSummary to ensure fresh data, not getWHTSummary (which may be stale)
  try {
    // CRITICAL: Use entityId instead of companyId (supports both Company and Business)
    const whtSummary = await whtService.updateWHTSummary(entityId, month, year);
    if (whtSummary && (whtSummary.totalWHTDeducted || 0) > 0) {
      if (yPos > pageHeight - 50) {
        doc.addPage();
        yPos = margin;
      }
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.text("Withholding Tax (WHT) Remittance Note", margin, yPos);
      yPos += 6;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.text(`Total WHT Deducted for ${period}: ${formatCurrency(whtSummary.totalWHTDeducted || 0)}`, margin, yPos);
      yPos += 5;
      // CRITICAL: Add null safety check for status
      const whtStatus = (whtSummary.status || "pending").toUpperCase();
      doc.text(`WHT Remittance Status: ${whtStatus}`, margin, yPos);
      yPos += 5;
      doc.setFontSize(7);
      doc.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
      doc.text("Note: WHT must be remitted separately to NRS (Nigeria Revenue Service) by the 21st of the following month.", margin, yPos);
      doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
      yPos += 8;
    }
  } catch (error) {
    // If WHT service fails, continue without WHT note
    console.error("Error fetching WHT summary for VAT return:", error);
  }

  // VAT Records Detail (if space allows)
  if (vatRecords.length > 0 && yPos < pageHeight - 60) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("VAT Transaction Details", margin, yPos);
    yPos += 8;

    // Check if we need a new page
    if (yPos + (vatRecords.length * 6) > pageHeight - 40) {
      doc.addPage();
      yPos = margin;
    }

    // Table Header
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    const detailColWidths = [30, 20, 50, 50, 30];
    const detailColX = [margin, margin + 30, margin + 50, margin + 100, pageWidth - margin - 30];
    
    doc.rect(margin, yPos - 4, pageWidth - 2 * margin, 6, "S");
    doc.text("Date", detailColX[0] + 2, yPos);
    doc.text("Type", detailColX[1] + 2, yPos);
    doc.text("Description", detailColX[2] + 2, yPos);
    doc.text("Invoice #", detailColX[3] + 2, yPos);
    doc.text("Amount", detailColX[4], yPos, { align: "right" });
    yPos += 6;

    // Table Rows (limit to fit on page)
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    let recordCount = 0;
    const maxRecords = Math.floor((pageHeight - yPos - 40) / 5);
    
    for (const record of vatRecords.slice(0, maxRecords)) {
      if (yPos > pageHeight - 20) {
        doc.addPage();
        yPos = margin;
      }
      
      // CRITICAL: Add null safety checks for VAT record values
      const vatRecordAmount = record.amount || 0;
      const vatRecordType = (record.type || "output").toUpperCase();
      const vatRecordDescription = record.description || "N/A";
      // CRITICAL: Add null safety check for transactionDate
      const transactionDate = record.transactionDate 
        ? formatDate(record.transactionDate) 
        : "N/A";
      
      doc.rect(margin, yPos - 4, pageWidth - 2 * margin, 5, "S");
      doc.text(transactionDate, detailColX[0] + 2, yPos);
      doc.text(vatRecordType, detailColX[1] + 2, yPos);
      const descLines = doc.splitTextToSize(vatRecordDescription, detailColWidths[2]);
      doc.text(descLines[0], detailColX[2] + 2, yPos);
      doc.text(record.invoiceId ? "Yes" : "N/A", detailColX[3] + 2, yPos);
      doc.text(formatCurrency(vatRecordAmount), detailColX[4], yPos, { align: "right" });
      yPos += Math.max(5, descLines.length * 3);
      recordCount++;
    }

    if (vatRecords.length > maxRecords) {
      yPos += 3;
      doc.setFontSize(7);
      doc.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
      doc.text(`Note: Showing ${maxRecords} of ${vatRecords.length} transactions. Full details available in system.`, margin, yPos);
      doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    }
  }

  // Add disclaimer footer
  addDisclaimerFooter(doc, pageWidth, pageHeight);

  // Add watermark if required
  if (isWatermarked) {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        addWatermark(doc, pageWidth, pageHeight, "taxcomply.ng");
    }
  }

  const pdfOutput = doc.output("arraybuffer");
  return Buffer.from(pdfOutput);
}

/**
 * Generates VAT Return Filing Support Document (Yearly Aggregated)
 */
export async function generateYearlyVATReturnPDF(
  entityId: Types.ObjectId,
  year: number,
  accountType: AccountType,
  isWatermarked: boolean = false
): Promise<Buffer> {
  // CRITICAL: Validate accountType
  if (!accountType || (accountType !== AccountType.Company && accountType !== AccountType.Business)) {
    throw new Error(`CRITICAL: accountType is required and must be AccountType.Company or AccountType.Business. Received: ${accountType || "undefined"}`);
  }

  // Get entity (Company or Business) for document header
  let entity: any;
  let entityForHeader: any;
  if (accountType === AccountType.Company) {
    entity = await Company.findById(entityId);
    if (!entity) {
      throw new Error("Company not found");
    }
    // Company structure matches addDocumentHeader expectations
    entityForHeader = entity;
  } else {
    entity = await Business.findById(entityId);
    if (!entity) {
      throw new Error("Business not found");
    }
    // Map Business structure to match addDocumentHeader expectations
    entityForHeader = {
      name: entity.name,
      tin: entity.tin || "",
      cacNumber: entity.businessRegistrationNumber || "", // Map businessRegistrationNumber to cacNumber for header
      address: entity.address || "",
      city: entity.city || "",
      state: entity.state || "",
      phoneNumber: entity.phoneNumber || "",
      email: entity.email || "",
    };
  }

  const vatService = (await import("../vat/service")).vatService;
  // CRITICAL: Use entityId (not companyId) - supports both Company and Business
  const yearlySummary = await vatService.getYearlyVATSummary(entityId, year, accountType);
  
  if (!yearlySummary) {
    throw new Error("Yearly VAT summary not found");
  }

  // Get monthly summaries for the year
  // CRITICAL: Use entityId (not companyId) - supports both Company and Business
  const monthlySummaries = await vatService.getVATSummariesForYear(entityId, year, accountType);

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;

  // entityForHeader is already formatted correctly (Company structure or Business mapped to Company structure)
  let yPos = addDocumentHeader(doc, pageWidth, entityForHeader, "ANNUAL VAT RETURN", `Year ${year}`);

  // Yearly Summary Section
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  doc.text("Annual VAT Computation Summary", margin, yPos);
  yPos += 8;

  // Summary Table
  const colWidths = [100, 60];
  const colXPositions = [margin, pageWidth - margin - 60];

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 8, "S");
  doc.text("Description", margin + 5, yPos);
  doc.text("Amount (NGN)", colXPositions[1], yPos);
  yPos += 8;

  // CRITICAL: Add null safety checks for all summary values
  const yearlyOutputVAT = yearlySummary.outputVAT || 0;
  const yearlyInputVAT = yearlySummary.inputVAT || 0;
  const yearlyNetVAT = yearlySummary.netVAT || 0;
  
  doc.setFont("helvetica", "normal");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Total Output VAT (VAT on Sales)", margin + 5, yPos);
  doc.text(formatCurrency(yearlyOutputVAT), colXPositions[1], yPos);
  yPos += 6;

  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Total Input VAT (VAT on Purchases)", margin + 5, yPos);
  doc.text(formatCurrency(yearlyInputVAT), colXPositions[1], yPos);
  yPos += 6;

  doc.setFont("helvetica", "bold");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Net VAT Payable/Refundable", margin + 5, yPos);
  doc.setTextColor(
    yearlyNetVAT >= 0 ? COLORS.primaryDark[0] : COLORS.warning[0],
    yearlyNetVAT >= 0 ? COLORS.primaryDark[1] : COLORS.warning[1],
    yearlyNetVAT >= 0 ? COLORS.primaryDark[2] : COLORS.warning[2]
  );
  doc.text(formatCurrency(yearlyNetVAT), colXPositions[1], yPos);
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  yPos += 10;

  // Monthly Breakdown
  if (monthlySummaries.length > 0) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Monthly Breakdown", margin, yPos);
    yPos += 8;

    // Check if we need a new page
    if (yPos + (monthlySummaries.length * 7) > pageHeight - 40) {
      doc.addPage();
      yPos = margin;
    }

    // Table Header
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    const monthColWidths = [40, 50, 50, 50];
    const monthColX = [margin, margin + 40, margin + 90, pageWidth - margin - 50];
    
    doc.rect(margin, yPos - 4, pageWidth - 2 * margin, 6, "S");
    doc.text("Month", monthColX[0] + 2, yPos);
    doc.text("Output VAT", monthColX[1], yPos, { align: "right" });
    doc.text("Input VAT", monthColX[2], yPos, { align: "right" });
    doc.text("Net VAT", monthColX[3], yPos, { align: "right" });
    yPos += 6;

    // Table Rows
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    for (const summary of monthlySummaries) {
      if (yPos > pageHeight - 20) {
        doc.addPage();
        yPos = margin;
      }
      
      // CRITICAL: Add null safety checks for monthly summary values
      const monthOutputVAT = summary.outputVAT || 0;
      const monthInputVAT = summary.inputVAT || 0;
      const monthNetVAT = summary.netVAT || 0;
      
      doc.rect(margin, yPos - 4, pageWidth - 2 * margin, 5, "S");
      doc.text(getMonthName(summary.month), monthColX[0] + 2, yPos);
      doc.text(formatCurrency(monthOutputVAT), monthColX[1], yPos, { align: "right" });
      doc.text(formatCurrency(monthInputVAT), monthColX[2], yPos, { align: "right" });
      doc.text(formatCurrency(monthNetVAT), monthColX[3], yPos, { align: "right" });
      yPos += 5;
    }
  }

  // WHT Remittance Note for Yearly VAT Return
  try {
    // CRITICAL: Aggregate monthly WHT summaries for accurate yearly totals
    // Using getWHTRecords and manual calculation may miss remittance status and pending amounts
    // Instead, aggregate monthly summaries which include remitted/pending amounts correctly
    let totalWHTDeducted = 0;
    let totalWHTRemitted = 0;
    let totalWHTPending = 0;
    let totalWHTRecordsCount = 0;
    
    // Aggregate all monthly summaries for the year
    for (let m = 1; m <= 12; m++) {
      try {
        const monthlySummary = await whtService.updateWHTSummary(entityId, m, year);
        if (monthlySummary) {
          totalWHTDeducted += monthlySummary.totalWHTDeducted || 0;
          totalWHTRemitted += monthlySummary.totalWHTRemitted || 0;
          totalWHTPending += monthlySummary.totalWHTPending || 0;
          totalWHTRecordsCount += monthlySummary.whtRecordsCount || 0;
        }
      } catch (error) {
        // If a month fails, continue with other months
        console.error(`Error fetching WHT summary for ${m}/${year}:`, error);
      }
    }
    
    if (totalWHTDeducted > 0) {
      if (yPos > pageHeight - 50) {
        doc.addPage();
        yPos = margin;
      }
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.text("Withholding Tax (WHT) Remittance Note", margin, yPos);
      yPos += 6;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.text(`Total WHT Deducted for ${year}: ${formatCurrency(totalWHTDeducted)}`, margin, yPos);
      yPos += 5;
      if (totalWHTRemitted > 0) {
        doc.text(`Total WHT Remitted for ${year}: ${formatCurrency(totalWHTRemitted)}`, margin, yPos);
        yPos += 5;
      }
      if (totalWHTPending > 0) {
        doc.setTextColor(COLORS.warning[0], COLORS.warning[1], COLORS.warning[2]);
        doc.text(`Total WHT Pending for ${year}: ${formatCurrency(totalWHTPending)}`, margin, yPos);
        doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
        yPos += 5;
      }
      doc.setFontSize(7);
      doc.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
      doc.text("Note: WHT must be remitted separately to NRS (Nigeria Revenue Service) by the 21st of the following month for each period.", margin, yPos);
      doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
      yPos += 8;
    }
  } catch (error) {
    // If WHT service fails, continue without WHT note
    console.error("Error fetching WHT summary for yearly VAT return:", error);
  }

  // Add disclaimer footer
  addDisclaimerFooter(doc, pageWidth, pageHeight);

  // Add watermark if required
  if (isWatermarked) {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        addWatermark(doc, pageWidth, pageHeight, "taxcomply.ng");
    }
  }

  const pdfOutput = doc.output("arraybuffer");
  return Buffer.from(pdfOutput);
}

/**
 * Generates PAYE Remittance Filing Support Document
 * Reference: NRS (Nigeria Revenue Service) PAYE Remittance Requirements
 * 
 * CRITICAL: This application only supports tax laws valid from 2026 onward per Nigeria Tax Act 2025.
 * NRS was rebranded to NRS (Nigeria Revenue Service) effective January 1, 2026.
 * CRITICAL: Supports both Company and Business accounts
 */
export async function generatePAYERemittancePDF(
  entityId: Types.ObjectId,
  month: number,
  year: number,
  accountType: AccountType,
  isWatermarked: boolean = false
): Promise<Buffer> {
  // CRITICAL: Validate accountType
  if (!accountType || (accountType !== AccountType.Company && accountType !== AccountType.Business)) {
    throw new Error(`CRITICAL: accountType is required and must be AccountType.Company or AccountType.Business. Received: ${accountType || "undefined"}`);
  }

  // Get entity (Company or Business) for document header
  let entity: any;
  let entityForHeader: any;
  if (accountType === AccountType.Company) {
    entity = await Company.findById(entityId);
    if (!entity) {
      throw new Error("Company not found");
    }
    // Company structure matches addDocumentHeader expectations
    entityForHeader = entity;
  } else {
    entity = await Business.findById(entityId);
    if (!entity) {
      throw new Error("Business not found");
    }
    // Map Business structure to match addDocumentHeader expectations
    entityForHeader = {
      name: entity.name,
      tin: entity.tin || "",
      cacNumber: entity.businessRegistrationNumber || "", // Map businessRegistrationNumber to cacNumber for header
      address: entity.address || "",
      city: entity.city || "",
      state: entity.state || "",
      phoneNumber: entity.phoneNumber || "",
      email: entity.email || "",
    };
  }

  const payrollService = (await import("../payroll/service")).payrollService;
  
  // Build query filter for payroll records based on accountType
  // CRITICAL: Use null instead of { $exists: false } because schema has default: null
  const payrollQueryFilter: any = {
    payrollMonth: month,
    payrollYear: year,
  };
  if (accountType === AccountType.Company) {
    payrollQueryFilter.companyId = entityId;
    payrollQueryFilter.businessId = null;
  } else if (accountType === AccountType.Business) {
    payrollQueryFilter.businessId = entityId;
    payrollQueryFilter.companyId = null;
  }

  // Get individual payroll records first to check if any exist
  const payrolls = await Payroll.find(payrollQueryFilter).populate("employeeId").sort({ createdAt: 1 });

  // Calculate totals directly from payrolls array (ensurePayrollSchedule doesn't return enriched totals)
  // This matches how calculatePayrollScheduleTotals works
  const totalEmployees = payrolls.length;
  const totalGrossSalary = payrolls.reduce((sum, p) => sum + (p.grossSalary || 0), 0);
  const totalPAYE = payrolls.reduce((sum, p) => sum + (p.paye || 0), 0);
  const totalNetSalary = payrolls.reduce((sum, p) => sum + (p.netSalary || 0), 0);
  
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;

  const period = `${getMonthName(month)} ${year}`;
  // entityForHeader is already formatted correctly (Company structure or Business mapped to Company structure)
  let yPos = addDocumentHeader(doc, pageWidth, entityForHeader, "PAYE REMITTANCE", period);

  // If no payroll records exist, show a helpful message instead of throwing an error
  if (payrolls.length === 0) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    doc.text("PAYE Remittance Summary", margin, yPos);
    yPos += 15;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
    const message = `No payroll records found for ${period}.`;
    const messageLines = doc.splitTextToSize(message, pageWidth - 2 * margin);
    doc.text(messageLines, margin, yPos);
    yPos += 10;

    doc.setFontSize(9);
    const instruction = "Please generate payroll for this period first before generating the PAYE remittance document.";
    const instructionLines = doc.splitTextToSize(instruction, pageWidth - 2 * margin);
    doc.text(instructionLines, margin, yPos);
    yPos += 15;

    // Add disclaimer footer
    addDisclaimerFooter(doc, pageWidth, pageHeight);

    const pdfOutput = doc.output("arraybuffer");
    return Buffer.from(pdfOutput);
  }

  // PAYE Summary Section
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  doc.text("PAYE Remittance Summary", margin, yPos);
  yPos += 8;

  // Summary Table
  const colWidths = [100, 60];
  const colXPositions = [margin, pageWidth - margin - 60];

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 8, "S");
  doc.text("Description", margin + 5, yPos);
  doc.text("Amount (NGN)", colXPositions[1], yPos);
  yPos += 8;

  // CRITICAL: Totals are calculated directly from payrolls array above
  // No need for payrollSchedule totals - they're already computed
  
  doc.setFont("helvetica", "normal");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Total Number of Employees", margin + 5, yPos);
  doc.text(totalEmployees.toString(), colXPositions[1], yPos);
  yPos += 6;

  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Total Gross Salary", margin + 5, yPos);
  doc.text(formatCurrency(totalGrossSalary), colXPositions[1], yPos);
  yPos += 6;

  doc.setFont("helvetica", "bold");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Total PAYE to Remit", margin + 5, yPos);
  doc.setTextColor(COLORS.primaryDark[0], COLORS.primaryDark[1], COLORS.primaryDark[2]);
  doc.text(formatCurrency(totalPAYE), colXPositions[1], yPos);
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  yPos += 6;

  doc.setFont("helvetica", "normal");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Total Net Salary", margin + 5, yPos);
  doc.text(formatCurrency(totalNetSalary), colXPositions[1], yPos);
  yPos += 10;

  // Employee Breakdown (if space allows)
  if (payrolls.length > 0 && yPos < pageHeight - 80) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Employee PAYE Breakdown", margin, yPos);
    yPos += 8;

    // Check if we need a new page
    if (yPos + (payrolls.length * 6) > pageHeight - 40) {
      doc.addPage();
      yPos = margin;
    }

    // Table Header
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    const empColWidths = [60, 50, 50, 30];
    const empColX = [margin, margin + 60, margin + 110, pageWidth - margin - 30];
    
    doc.rect(margin, yPos - 4, pageWidth - 2 * margin, 6, "S");
    doc.text("Employee ID", empColX[0] + 2, yPos);
    doc.text("Gross Salary", empColX[1], yPos, { align: "right" });
    doc.text("Taxable Income", empColX[2], yPos, { align: "right" });
    doc.text("PAYE", empColX[3], yPos, { align: "right" });
    yPos += 6;

    // Table Rows (limit to fit on page)
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    const maxRecords = Math.floor((pageHeight - yPos - 40) / 5);
    
    for (const payroll of payrolls.slice(0, maxRecords)) {
      if (yPos > pageHeight - 20) {
        doc.addPage();
        yPos = margin;
      }
      
      const employee = (payroll as any).employeeId;
      const employeeId = employee?.employeeId || "N/A";
      
      // CRITICAL: Add null safety checks for payroll values
      const grossSalary = payroll.grossSalary || 0;
      const taxableIncome = payroll.taxableIncome || 0;
      const paye = payroll.paye || 0;
      
      doc.rect(margin, yPos - 4, pageWidth - 2 * margin, 5, "S");
      doc.text(employeeId, empColX[0] + 2, yPos);
      doc.text(formatCurrency(grossSalary), empColX[1], yPos, { align: "right" });
      doc.text(formatCurrency(taxableIncome), empColX[2], yPos, { align: "right" });
      doc.text(formatCurrency(paye), empColX[3], yPos, { align: "right" });
      yPos += 5;
    }

    if (payrolls.length > maxRecords) {
      yPos += 3;
      doc.setFontSize(7);
      doc.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
      doc.text(`Note: Showing ${maxRecords} of ${payrolls.length} employees. Full details available in system.`, margin, yPos);
      doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    }
  }

  // WHT Credits Section for PAYE Remittance
  // WHT deducted from payments to employees can offset PIT (Personal Income Tax)
  // CRITICAL: Use updateWHTSummary to ensure fresh data, not getWHTSummary (which may be stale)
  try {
    // Get WHT credits for employees (individuals) for this period
    // Note: In a full implementation, you'd track which employees received WHT
    // For now, we show aggregate WHT information
    // CRITICAL: Use entityId instead of companyId (supports both Company and Business)
    const whtSummary = await whtService.updateWHTSummary(entityId, month, year);
    if (whtSummary && (whtSummary.totalWHTDeducted || 0) > 0) {
      if (yPos > pageHeight - 60) {
        doc.addPage();
        yPos = margin;
      }
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.text("Withholding Tax (WHT) Information", margin, yPos);
      yPos += 6;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.text(`Total WHT Deducted for ${period}: ${formatCurrency(whtSummary.totalWHTDeducted || 0)}`, margin, yPos);
      yPos += 5;
      // CRITICAL: Add null safety check for status
      const whtStatus = (whtSummary.status || "pending").toUpperCase();
      doc.text(`WHT Remittance Status: ${whtStatus}`, margin, yPos);
      yPos += 5;
      doc.setFontSize(7);
      doc.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
      doc.text("Note: WHT deducted from payments to individuals can be used as tax credit to offset PIT liability.", margin, yPos);
      yPos += 4;
      doc.text("WHT must be remitted separately to NRS (Nigeria Revenue Service) by the 21st of the following month.", margin, yPos);
      doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
      yPos += 8;
    }
  } catch (error) {
    // If WHT service fails, continue without WHT note
    console.error("Error fetching WHT summary for PAYE remittance:", error);
  }

  // Add disclaimer footer
  addDisclaimerFooter(doc, pageWidth, pageHeight);

  // Add watermark if required
  if (isWatermarked) {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        addWatermark(doc, pageWidth, pageHeight, "taxcomply.ng");
    }
  }

  const pdfOutput = doc.output("arraybuffer");
  return Buffer.from(pdfOutput);
}

/**
 * Generates Company Income Tax (CIT) Return Filing Support Document
 * Reference: NRS (Nigeria Revenue Service) CIT Return Requirements (Annual)
 * 
 * CRITICAL: This application only supports tax laws valid from 2026 onward per Nigeria Tax Act 2025.
 * NRS was rebranded to NRS (Nigeria Revenue Service) effective January 1, 2026.
 */
export async function generateCITReturnPDF(
  companyId: Types.ObjectId,
  year: number,
  isWatermarked: boolean = false
): Promise<Buffer> {
  const company = await Company.findById(companyId);
  if (!company) {
    throw new Error("Company not found");
  }
  
  // CRITICAL: Annual turnover is now computed from invoices, not stored
  // Calculate annual turnover from paid invoices for the tax year
  const companyService = (await import("../company/service")).companyService;
  let annualTurnover = 0;
  try {
    annualTurnover = await companyService.calculateAnnualTurnover(companyId, year);
  } catch (error) {
    // CRITICAL: Fail loudly if turnover calculation fails
    throw new Error(
      `CRITICAL: Cannot generate CIT PDF - failed to calculate annual turnover from invoices. ` +
      `Company ID: ${companyId.toString()}, Company Name: ${company.name}, Tax Year: ${year}. ` +
      `Error: ${error instanceof Error ? error.message : String(error)}. ` +
      `Annual turnover calculation from invoices is required for tax classification.`
    );
  }

  // CRITICAL: Log company data for debugging tax classification
  console.log("[generateCITReturnPDF] Company data for tax classification:", {
    companyId: companyId.toString(),
    companyName: company.name,
    annualTurnover, // Computed from invoices
    fixedAssets: company.fixedAssets,
    storedTaxClassification: company.taxClassification,
    year,
  });

  // CRITICAL: VAT information is NOT included in CIT Return PDF
  // CIT and VAT are separate taxes with separate filing requirements per NRS regulations.
  // CIT Return should only contain CIT-specific information (revenue, expenses, taxable profit, CIT calculation, WHT credits).
  // VAT information belongs in VAT Return documents, which are filed separately.

  // Get all PAID invoices for the year to calculate revenue
  // CRITICAL: For CIT purposes, only paid invoices should be counted as revenue
  // Unpaid invoices don't represent actual revenue received
  const Invoice = (await import("../invoice/entity")).default;
  const yearStart = new Date(year, 0, 1);
  const yearEnd = new Date(year, 11, 31, 23, 59, 59);
  
  const invoiceQuery = {
    companyId,
    issueDate: { $gte: yearStart, $lte: yearEnd },
    status: InvoiceStatus.Paid, // CRITICAL: Only count paid invoices as revenue
  };
  
  console.log("[generateCITReturnPDF] Invoice query:", {
    companyId: companyId.toString(),
    status: InvoiceStatus.Paid,
    yearStart: yearStart.toISOString(),
    yearEnd: yearEnd.toISOString(),
    query: invoiceQuery,
  });
  
  const invoices = await Invoice.find(invoiceQuery);
  
  console.log("[generateCITReturnPDF] Paid invoices found:", {
    invoiceCount: invoices.length,
    totalRevenue: invoices.reduce((sum, inv) => sum + (inv.subtotal || 0), 0),
    sampleInvoices: invoices.slice(0, 3).map(inv => ({
      _id: inv._id?.toString(),
      invoiceNumber: inv.invoiceNumber,
      subtotal: inv.subtotal,
      status: inv.status,
      issueDate: inv.issueDate?.toISOString(),
    })),
  });

  // CRITICAL: Use subtotal (excludes VAT) for revenue calculation
  // Invoice subtotal is the base amount before VAT, which is correct for CIT revenue
  // This is the same calculation used in calculateAnnualTurnover
  const totalRevenue = invoices.reduce((sum, inv) => sum + (inv.subtotal || 0), 0);
  
  // CRITICAL: Validate that computed revenue matches calculated annual turnover
  // Annual turnover should equal total revenue (both are sum of paid invoice subtotals)
  if (Math.abs(totalRevenue - annualTurnover) > 0.01) {
    logger.warn("Revenue mismatch in CIT PDF generation", {
      companyId: companyId.toString(),
      year,
      calculatedRevenue: totalRevenue,
      calculatedAnnualTurnover: annualTurnover,
      difference: Math.abs(totalRevenue - annualTurnover),
    });
    // Use the more recent calculation (annualTurnover from service) for consistency
  }
  
  console.log("[generateCITReturnPDF] Total revenue calculated:", {
    totalRevenue,
    annualTurnover, // From service calculation
    year,
    companyId: companyId.toString(),
  });
  
  // Get total tax-deductible expenses for the year
  // Only tax-deductible expenses can reduce taxable profit for CIT purposes
  // CRITICAL: CIT is Company-only, use companyId and AccountType.Company enum
  const Expense = (await import("../expense/entity")).default;
  const expenseQuery = {
    companyId, // Use companyId directly (ObjectId)
    accountType: AccountType.Company, // CRITICAL: Use enum, not string literal
    isTaxDeductible: true, // Only include tax-deductible expenses
    date: { $gte: yearStart, $lte: yearEnd },
  };
  
  console.log("[generateCITReturnPDF] Expense query:", {
    companyId: companyId.toString(),
    accountType: AccountType.Company,
    yearStart: yearStart.toISOString(),
    yearEnd: yearEnd.toISOString(),
    query: expenseQuery,
  });
  
  const expenses = await Expense.find(expenseQuery);
  
  console.log("[generateCITReturnPDF] Expenses found:", {
    expenseCount: expenses.length,
    totalAmount: expenses.reduce((sum, exp) => sum + (exp.amount || 0), 0),
    sampleExpenses: expenses.slice(0, 3).map(exp => ({
      _id: exp._id?.toString(),
      description: exp.description,
      amount: exp.amount,
      date: exp.date?.toISOString(),
      accountType: exp.accountType,
      companyId: exp.companyId?.toString(),
    })),
  });
  
  // CRITICAL: For CIT, expenses should exclude VAT (VAT is separate tax)
  // expense.amount is the gross expense amount (before VAT)
  // If VAT was paid on expense, it's tracked separately in expense.vatAmount
  // For CIT calculation, we use the net expense amount (amount - vatAmount if VAT was included)
  // However, based on the expense model, amount is the base amount, and vatAmount is separate
  // So we use amount directly (which is the expense base, excluding VAT)
  const totalExpenses = expenses.reduce((sum, exp) => sum + (exp.amount || 0), 0);
  
  console.log("[generateCITReturnPDF] Total expenses calculated:", {
    totalExpenses,
    year,
    companyId: companyId.toString(),
  });

  // Calculate taxable profit for CIT computation
  // CRITICAL: Formula per Nigeria Tax Act 2025: Taxable Profit = Total Revenue - Total Expenses
  // Negative values represent losses (which are not taxable but should be shown in the PDF)
  // NOTE: companyService is already declared above at line 989
  const taxableProfit = totalRevenue - totalExpenses;
  
  console.log("[generateCITReturnPDF] Taxable profit calculation:", {
    totalRevenue,
    totalExpenses,
    taxableProfit,
    calculation: `${totalRevenue} - ${totalExpenses} = ${taxableProfit}`,
    isLoss: taxableProfit < 0,
    year,
    companyId: companyId.toString(),
  });
  
  // Use company service method to calculate CIT with WHT credits
  // CRITICAL: This method determines tax classification from annualTurnover and fixedAssets
  // and calculates the appropriate CIT rate (0% Small, 20% Medium, 30% Large)
  let citComputation;
  try {
    citComputation = await companyService.calculateCITWithWHTCredits(
      companyId,
      taxableProfit,
      year
    );
    
    console.log("[generateCITReturnPDF] CIT computation from service:", {
      taxClassification: citComputation.taxClassification,
      citRate: citComputation.citRate,
      citRatePercentage: `${(citComputation.citRate * 100).toFixed(0)}%`,
      citBeforeWHT: citComputation.citBeforeWHT,
      whtCredits: citComputation.whtCredits,
      citAfterWHT: citComputation.citAfterWHT,
      companyId: companyId.toString(),
      year,
    });
  } catch (error: any) {
    // CRITICAL: Fallback calculation for PDF generation if service fails
    // This should rarely happen, but we need it for PDF generation resilience
    console.error("CRITICAL: Error calculating CIT with WHT credits in PDF generation, using fallback:", error);
    
    // CRITICAL: Determine tax classification - no fallback, fail loudly if cannot determine
    let taxClassification: TaxClassification;
    if (company.taxClassification) {
      taxClassification = company.taxClassification as TaxClassification;
    } else {
      // CRITICAL: Calculate tax classification from computed annual turnover and fixed assets
      // Annual turnover is computed from invoices (already calculated above)
      // Per Nigeria Tax Act 2025 (effective 2026):
      // - Small: turnover <= ₦50M AND fixedAssets <= ₦250M → 0% CIT (Strict)
      // - Other: turnover > ₦50M → 30% CIT
      taxClassification = companyService.calculateTaxClassification(
        annualTurnover, // Use computed turnover from invoices
        company.fixedAssets,
        year
      );
      
      console.log("[generateCITReturnPDF] Calculated tax classification (fallback):", {
        annualTurnover, // Computed from invoices
        fixedAssets: company.fixedAssets,
        calculatedClassification: taxClassification,
        year,
        thresholds: {
          smallCompany: "turnover <= ₦50M AND fixedAssets <= ₦250M → 0% CIT",
          mediumCompany: "turnover > ₦50M → 30% CIT",
          largeCompany: "turnover > ₦500M → 30% CIT",
        },
      });
    }

    // CRITICAL: Normalize tax classification to ensure it matches enum values
    let normalizedTaxClassification: TaxClassification;
    
    if (typeof taxClassification === "string") {
      const normalized = taxClassification.toLowerCase().trim();
      if (normalized === "small_company" || normalized === "smallcompany") {
        normalizedTaxClassification = TaxClassification.SmallCompany;
      } else if (normalized === "medium") {
        normalizedTaxClassification = TaxClassification.Medium;
      } else if (normalized === "large") {
        normalizedTaxClassification = TaxClassification.Large;
      } else {
        throw new Error(
          `CRITICAL: Invalid tax classification value in PDF generation: "${taxClassification}" (normalized: "${normalized}"). ` +
          `Must be one of: ${TaxClassification.SmallCompany}, ${TaxClassification.Medium}, ${TaxClassification.Large}. ` +
          `Company ID: ${companyId.toString()}, Tax Year: ${year}.`
        );
      }
    } else if (taxClassification === TaxClassification.SmallCompany || 
               taxClassification === TaxClassification.Medium || 
               taxClassification === TaxClassification.Large) {
      normalizedTaxClassification = taxClassification;
    } else {
      throw new Error(
        `CRITICAL: Invalid tax classification type or value in PDF generation. ` +
        `Type: ${typeof taxClassification}, Value: ${taxClassification}. ` +
        `Must be TaxClassification enum value. ` +
        `Company ID: ${companyId.toString()}, Tax Year: ${year}.`
      );
    }

    // Determine Exemption Status based on Turnover and Year
    // CRITICAL: Decouple Tax Classification (Structural) from Tax Exemption (Fiscal)
    const { isCITExempt } = await import("../tax/calculator");
    const isExempt = isCITExempt(annualTurnover, year);

    // Determine Rate
    // If exempt -> 0%
    // If not exempt -> Standard Rate (30%)
    const standardRate = NRS_CIT_RATE / 100;
    const citRate = isExempt ? 0 : standardRate;

    // Legacy mapping for logging/debugging (optional, but keep variable for consistency)
    const CIT_RATES: Record<TaxClassification, number> = {
      [TaxClassification.SmallCompany]: 0, 
      [TaxClassification.Medium]: isExempt ? 0 : standardRate, 
      [TaxClassification.Large]: standardRate, 
    };

    // Verify consistency (optional)
    const legacyRate = CIT_RATES[normalizedTaxClassification];
    if (Math.abs(legacyRate - citRate) > 0.001) {
       console.warn("[generateCITReturnPDF] Discrepancy between calculated CIT rate and legacy table lookup", { calculated: citRate, legacy: legacyRate });
    }
    
    // Proceed with calculated citRate
    
    if (citRate === undefined || citRate === null) {
      throw new Error(
        `CRITICAL: CIT rate invalid in PDF generation fallback. ` +
        `Company ID: ${companyId.toString()}, Tax Year: ${year}.`
      );
    }
    
    // CRITICAL: Validate citRate is a valid number - fail loudly if invalid
    if (typeof citRate !== "number" || isNaN(citRate) || !isFinite(citRate)) {
      throw new Error(
        `CRITICAL: Invalid CIT rate in PDF generation. Type: ${typeof citRate}, Value: ${citRate}. ` +
        `Tax classification: ${normalizedTaxClassification}. ` +
        `Company ID: ${companyId.toString()}, Tax Year: ${year}.`
      );
    }
    
    // CRITICAL: Calculate CIT before WHT credits using the classification-based rate
    const citBeforeWHT = Math.max(0, taxableProfit * citRate);
    citComputation = {
      taxClassification: normalizedTaxClassification,
      citRate,
      citBeforeWHT,
      whtCredits: 0,
      citAfterWHT: citBeforeWHT,
      creditApplied: 0,
    };
  }
  
  const { taxClassification, citRate, citBeforeWHT, whtCredits: totalWHTCredits, citAfterWHT: citPayable, creditApplied } = citComputation;
  
  // CRITICAL: Calculate Development Levy per Nigeria Tax Act 2025 (effective 2026)
  // Development Levy applies to Medium and Large companies only (Small companies are exempt)
  // Rate: 4% for 2026, decreasing annually to 2% by 2030
  // Base: Assessable profit (taxable profit) - same as CIT base
  let developmentLevy = 0;
  try {
    developmentLevy = calculateDevelopmentLevy(
      taxableProfit > 0 ? taxableProfit : 0, // Only apply on profit, not losses
      taxClassification,
      year
    );
  } catch (error) {
    console.error("Error calculating Development Levy:", error);
    // Continue with 0 levy if calculation fails
    developmentLevy = 0;
  }
  
  // CRITICAL: Calculate Total Tax Payable = CIT After WHT + Development Levy
  // This represents the total tax obligation to NRS (Nigeria Revenue Service)
  const totalTaxPayable = citPayable + developmentLevy;
  
  // Get WHT summary for the year
  let whtSummary = null;
  try {
    // CRITICAL: Aggregate monthly WHT summaries for accurate yearly totals
    // Using getWHTRecords and manual calculation may miss remittance status and pending amounts
    // Instead, aggregate monthly summaries which include remitted/pending amounts correctly
    let totalWHTDeducted = 0;
    let totalWHTRemitted = 0;
    let totalWHTPending = 0;
    let totalWHTRecordsCount = 0;
    
    // Aggregate all monthly summaries for the year
    // CRITICAL: CIT is Company-only, so use companyId (not entityId)
    for (let m = 1; m <= 12; m++) {
      try {
        const monthlySummary = await whtService.updateWHTSummary(companyId, m, year);
        if (monthlySummary) {
          totalWHTDeducted += monthlySummary.totalWHTDeducted || 0;
          totalWHTRemitted += monthlySummary.totalWHTRemitted || 0;
          totalWHTPending += monthlySummary.totalWHTPending || 0;
          totalWHTRecordsCount += monthlySummary.whtRecordsCount || 0;
        }
      } catch (error) {
        // If a month fails, continue with other months
        console.error(`Error fetching WHT summary for ${m}/${year}:`, error);
      }
    }
    
    whtSummary = {
      totalWHTDeducted,
      totalWHTRemitted,
      totalWHTPending,
      totalWHTCredits,
      recordsCount: totalWHTRecordsCount,
    };
  } catch (error) {
    console.error("Error fetching WHT summary for CIT return:", error);
  }

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;

  let yPos = addDocumentHeader(doc, pageWidth, company, "Company Income Tax RETURN", `Tax Year ${year}`);

  // Company Classification Section
  // CRITICAL: Display annual turnover and fixed assets to show basis for tax classification
  // Per Nigeria Tax Act 2025 (effective 2026):
  // - Small: turnover ≤ ₦50M AND fixedAssets ≤ ₦250M → 0% CIT
  // - Other: turnover > ₦50M → 30% CIT
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Tax Classification", margin, yPos);
  yPos += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  
  // Display classification using human-readable label
  const classificationLabel = getTaxClassificationLabel(taxClassification);
  doc.text(`Classification: ${classificationLabel}`, margin, yPos);
  yPos += 5;
  
  // Display annual turnover (computed from invoices)
  doc.text(`Computed Annual Turnover (from available records): ${formatCurrency(annualTurnover)}`, margin, yPos);
  yPos += 5;

  // Disclaimer for turnover
  doc.setFontSize(7);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
  doc.text("Note: Turnover is derived from gross income per financial statements and may differ from invoiced amounts.", margin, yPos);
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  yPos += 8;
  
  // Display fixed assets (required for Small vs Medium classification)
  if (company.fixedAssets !== undefined && company.fixedAssets !== null) {
    doc.text(`Fixed Assets: ${formatCurrency(company.fixedAssets)}`, margin, yPos);
    yPos += 5;
  }
  
  // Display the classification criteria for transparency
  // CRITICAL: Use "NGN" instead of ₦ symbol and use words instead of symbols to avoid PDF rendering issues
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
  if (taxClassification === TaxClassification.SmallCompany) {
    doc.text("(Small Company: classified based on statutory turnover thresholds as prescribed by applicable tax law for the relevant year)", margin, yPos);
  } else if (taxClassification === TaxClassification.Medium) {
    doc.text("(Other Companies: classified based on statutory turnover thresholds as prescribed by applicable tax law for the relevant year)", margin, yPos);
  } else if (taxClassification === TaxClassification.Large) {
    doc.text("(Large Company: classified based on statutory turnover thresholds as prescribed by applicable tax law for the relevant year)", margin, yPos);
  }
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  yPos += 8;

  // CIT Computation Section
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("CIT Computation", margin, yPos);
  yPos += 8;

  // Computation Table
  const colWidths = [100, 60];
  const colXPositions = [margin, pageWidth - margin - 60];

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 8, "S");
  doc.text("Description", margin + 5, yPos);
  doc.text("Amount (NGN)", colXPositions[1], yPos);
  yPos += 8;

  doc.setFont("helvetica", "normal");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Total Revenue (Invoiced Sales)", margin + 5, yPos);
  doc.text(formatCurrency(totalRevenue), colXPositions[1], yPos);
  yPos += 6;

  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Total Expenses", margin + 5, yPos);
  doc.text(formatCurrency(totalExpenses), colXPositions[1], yPos);
  yPos += 6;

  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  // CRITICAL: Show "Taxable Profit" for positive values, "Taxable Loss" for negative values
  // Calculation: taxableProfit = totalRevenue - totalExpenses (correct formula per Nigeria Tax Act 2025)
  const profitLabel = taxableProfit >= 0 ? "Taxable Profit" : "Taxable Loss";
  doc.text(profitLabel, margin + 5, yPos);
  doc.text(formatCurrency(taxableProfit), colXPositions[1], yPos);
  yPos += 6;

  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("CIT Rate", margin + 5, yPos);
  const citRateDisplay = citRate === 0 ? "0% (Small Company Exemption)" : `${(citRate * 100).toFixed(0)}%`;
  doc.text(citRateDisplay, colXPositions[1], yPos);
  yPos += 6;

  doc.setFont("helvetica", "bold");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("CIT Before WHT Credits", margin + 5, yPos);
  doc.text(formatCurrency(citBeforeWHT), colXPositions[1], yPos);
  yPos += 6;

  // WHT Credits Section
  // CRITICAL: Show WHT credits line in computation if CIT before WHT > 0
  // This ensures audit-ready transparency in the computation flow
  // Use creditApplied (amount actually applied) for the computation table
  if (citBeforeWHT > 0) {
    doc.setFont("helvetica", "normal");
    doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
    doc.text("Less: WHT Credits Applied", margin + 5, yPos);
    doc.setTextColor(COLORS.primaryDark[0], COLORS.primaryDark[1], COLORS.primaryDark[2]);
    // Show the amount actually applied (0 if no credits applied)
    doc.text(`(${formatCurrency(creditApplied || 0)})`, colXPositions[1], yPos);
    doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    yPos += 6;
  }

  // CIT After WHT Credits
  doc.setFont("helvetica", "bold");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("CIT After WHT Credits", margin + 5, yPos);
  doc.text(formatCurrency(citPayable), colXPositions[1], yPos);
  yPos += 6;
  
  // Development Levy Section
  // CRITICAL: Development Levy applies to Medium and Large companies only (per Nigeria Tax Act 2025)
  if (developmentLevy > 0) {
    doc.setFont("helvetica", "normal");
    doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
    // Calculate levy rate for display (4% for 2026, decreasing to 2% by 2030)
    const levyRate = year >= 2030 ? 0.02 : 
                     year === 2029 ? 0.025 : 
                     year === 2028 ? 0.03 : 
                     year === 2027 ? 0.035 : 0.04;
    doc.text(`Add: Development Levy (${(levyRate * 100).toFixed(1)}%)`, margin + 5, yPos);
    doc.text(formatCurrency(developmentLevy), colXPositions[1], yPos);
    yPos += 6;
  }
  
  // Total Tax Payable
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 8, "S");
  doc.text("Total Tax Payable", margin + 5, yPos);
  doc.setTextColor(COLORS.primaryDark[0], COLORS.primaryDark[1], COLORS.primaryDark[2]);
  doc.text(formatCurrency(totalTaxPayable), colXPositions[1], yPos);
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  doc.setFontSize(9);
  yPos += 10;

  // WHT Information Section
  if (whtSummary && whtSummary.totalWHTDeducted > 0) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Withholding Tax (WHT) Information", margin, yPos);
    yPos += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(`Total WHT Deducted: ${formatCurrency(whtSummary.totalWHTDeducted)}`, margin, yPos);
    yPos += 5;
    if (whtSummary.totalWHTRemitted > 0) {
      doc.text(`Total WHT Remitted: ${formatCurrency(whtSummary.totalWHTRemitted)}`, margin, yPos);
      yPos += 5;
    }
    if (whtSummary.totalWHTPending > 0) {
      doc.setTextColor(COLORS.warning[0], COLORS.warning[1], COLORS.warning[2]);
      doc.text(`Total WHT Pending: ${formatCurrency(whtSummary.totalWHTPending)}`, margin, yPos);
      doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
      yPos += 5;
    }
    // CRITICAL: Show the actual amount of WHT credits applied to reduce CIT liability
    // creditApplied comes from calculateCITWithWHTCredits and represents the amount actually used
    // whtSummary.totalWHTCredits is the total available credits (may not all be applied)
    // CRITICAL: Show both available and applied WHT credits for transparency
    // Available credits = totalWHTDeducted (WHT deducted from payments, available as tax credit)
    // Applied credits = creditApplied (amount actually used to reduce CIT in this computation)
    // NOTE: WHT deducted is available as credit regardless of remittance status per NRS regulations
    doc.text(`WHT Credits Available: ${formatCurrency(whtSummary.totalWHTDeducted || 0)}`, margin, yPos);
    yPos += 5;
    doc.text(`WHT Credits Applied: ${formatCurrency(creditApplied || 0)}`, margin, yPos);
    yPos += 5;
    // Explicitly show carry forward amount for clarity
    const carryForward = Math.max(0, (whtSummary.totalWHTDeducted || 0) - (creditApplied || 0));
    if (carryForward > 0) {
      doc.text(`WHT Credits Carried Forward: ${formatCurrency(carryForward)}`, margin, yPos);
      yPos += 5;
    }
    doc.text(`WHT Records: ${whtSummary.recordsCount || 0}`, margin, yPos);
    yPos += 5;
    doc.setFontSize(7);
    doc.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
    doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    yPos += 8;
  }

  // CRITICAL: VAT information removed from CIT Return PDF
  // CIT (Company Income Tax) and VAT (Value Added Tax) are separate taxes with separate filing requirements.
  // CIT returns should only contain CIT-related information (revenue, expenses, taxable profit, CIT calculation, WHT credits).
  // VAT information belongs in VAT Return documents, not CIT Return documents.
  // This aligns with NRS (Nigeria Revenue Service) filing requirements where each tax has its own separate return form.

  // Important Notes
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("Important Notes:", margin, yPos);
  yPos += 6; // Match spacing with "Related Tax Information" header
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7); // Further reduced font size to prevent overflow with long text
  // CRITICAL: Notes for CIT Return per Nigeria Tax Act 2025 (effective 2026)
  // Each note appears only once - no duplication
  const notes = [
    "This computation is based on available data in the system and must be verified with your accounting records.",
    "Small Companies (annual turnover <= NGN 50,000,000 AND fixed assets <= NGN 250,000,000) are exempt from CIT based on the Nigeria Tax Reform Acts as enacted and effective for the 2026 tax year, including transitional provisions where applicable.",
    "Development Levy applies to Medium and Large companies at 4% (where applicable) for the relevant tax year.",
    "WHT deducted is available as a tax credit and may be carried forward to offset future Company Income Tax liabilities, subject to tax authority rules.",
    "Total Tax Payable equals CIT After WHT Credits plus Development Levy (where applicable).",
    "CIT filing deadline: as prescribed by the tax authority (generally within 6 months after the accounting year-end).",
    "Consult a qualified tax advisor for complex tax situations or if you have questions about your tax obligations.",
  ];
  
  // Account for bullet point (•) and spacing
  const bulletWidth = 5; // Space for bullet point
  const noteMaxWidth = pageWidth - 2 * margin - bulletWidth;
  
  for (const note of notes) {
    // Ensure we have enough space for footer (footer needs ~25mm from bottom)
    if (yPos > pageHeight - 30) {
      doc.addPage();
      yPos = margin;
    }
    
    // Add bullet point and split long text into multiple lines
    const noteText = `• ${note}`;
    const lines = doc.splitTextToSize(noteText, noteMaxWidth);
    
    // CRITICAL: Render each line individually to ensure no duplication
    // Iterate through lines array and render each line once
    if (Array.isArray(lines)) {
      for (const line of lines) {
        // Check space before each line
        if (yPos > pageHeight - 30) {
          doc.addPage();
          yPos = margin;
        }
        // Render line as string to ensure single rendering (avoid array auto-rendering duplication)
        if (typeof line === 'string' && line.trim().length > 0) {
          doc.text(line, margin, yPos);
          yPos += 5;
        }
      }
    } else if (typeof lines === 'string' && lines.trim().length > 0) {
      // Single line case
      if (yPos > pageHeight - 30) {
        doc.addPage();
        yPos = margin;
      }
      doc.text(lines, margin, yPos);
      yPos += 5;
    }
  }

  // Add disclaimer footer - ensure we have space
  if (yPos > pageHeight - 25) {
    doc.addPage();
  }
  addDisclaimerFooter(doc, pageWidth, pageHeight);

  // Add watermark if required
  if (isWatermarked) {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        addWatermark(doc, pageWidth, pageHeight, "taxcomply.ng");
    }
  }

  const pdfOutput = doc.output("arraybuffer");
  return Buffer.from(pdfOutput);
}

/**
 * Generates WHT Remittance PDF document for NRS (Nigeria Revenue Service) filing
 * Reference: NRS (Nigeria Revenue Service) WHT Regulations effective 2026+ - https://www.nrs.gov.ng/
 * 
 * CRITICAL: This application only supports tax laws valid from 2026 onward per Nigeria Tax Act 2025.
 * NRS was rebranded to NRS (Nigeria Revenue Service) effective January 1, 2026.
 * 
 * WHT must be remitted within 21 days of deduction (by 21st of following month)
 */
export async function generateWHTRemittancePDF(
  entityId: Types.ObjectId,
  month: number,
  year: number,
  accountType: AccountType,
  isWatermarked: boolean = false
): Promise<Buffer> {
  let company: any = null;

  if (accountType === AccountType.Company) {
    company = await Company.findById(entityId);
  } else if (accountType === AccountType.Business) {
    const { default: Business } = await import("../business/entity");
    company = await Business.findById(entityId);
  }

  if (!company) {
    throw new Error(`${accountType === AccountType.Company ? "Company" : "Business"} not found`);
  }

  // Get WHT records for the period
  // Get WHT records for the period
  const whtRecords = await whtService.getWHTRecords(entityId, { month, year });
  
  // Get WHT summary
  const summary = await whtService.updateWHTSummary(entityId, month, year);
  
  // Get remittance record if exists
  const { WHTRemittance } = await import("../wht/entity");
  const remittance = await WHTRemittance.findOne({
    companyId: entityId,
    remittanceMonth: month,
    remittanceYear: year,
  }).lean();

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;

  const period = `${getMonthName(month)} ${year}`;
  let yPos = addDocumentHeader(doc, pageWidth, company, "WHT REMITTANCE", period);

  // If no WHT records exist, show a helpful message
  if (whtRecords.length === 0) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    doc.text("WHT Remittance Summary", margin, yPos);
    yPos += 15;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
    const message = `No WHT records found for ${period}.`;
    const messageLines = doc.splitTextToSize(message, pageWidth - 2 * margin);
    doc.text(messageLines, margin, yPos);
    yPos += 10;

    doc.setFontSize(9);
    const instruction = "WHT records are automatically created when you deduct WHT from invoices or expenses. If you have WHT deductions, ensure they are properly recorded.";
    const instructionLines = doc.splitTextToSize(instruction, pageWidth - 2 * margin);
    doc.text(instructionLines, margin, yPos);
    yPos += 15;

    // Add disclaimer footer
    addDisclaimerFooter(doc, pageWidth, pageHeight);

    const pdfOutput = doc.output("arraybuffer");
    return Buffer.from(pdfOutput);
  }

  // WHT Summary Section
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  doc.text("WHT Remittance Summary", margin, yPos);
  yPos += 8;

  // Summary Table
  const colWidths = [100, 60];
  const colXPositions = [margin, pageWidth - margin - 60];

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 8, "S");
  doc.text("Description", margin + 5, yPos);
  doc.text("Amount (NGN)", colXPositions[1], yPos);
  yPos += 8;

  doc.setFont("helvetica", "normal");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Total WHT Deducted", margin + 5, yPos);
  doc.text(formatCurrency(summary.totalWHTDeducted || 0), colXPositions[1], yPos);
  yPos += 6;

  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Total WHT Remitted", margin + 5, yPos);
  doc.text(formatCurrency(summary.totalWHTRemitted || 0), colXPositions[1], yPos);
  yPos += 6;

  doc.setFont("helvetica", "bold");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Pending Remittance", margin + 5, yPos);
  doc.setTextColor(COLORS.warning[0], COLORS.warning[1], COLORS.warning[2]);
  doc.text(formatCurrency(summary.totalWHTPending || 0), colXPositions[1], yPos);
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  yPos += 6;

  doc.setFont("helvetica", "normal");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Number of WHT Records", margin + 5, yPos);
  doc.text((summary.whtRecordsCount || 0).toString(), colXPositions[1], yPos);
  yPos += 10;

  // Remittance Status
  if (remittance) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("Remittance Status", margin, yPos);
    yPos += 6;

    doc.setFont("helvetica", "normal");
    // CRITICAL: Add null safety check for remittanceDate
    // If remittance is marked as "remitted" but date is missing, show status without date
    const statusText = remittance.status === RemittanceStatus.Remitted 
      ? remittance.remittanceDate
        ? `Remitted on ${formatDate(remittance.remittanceDate)}`
        : "Remitted (date not recorded)"
      : remittance.status === RemittanceStatus.Overdue
      ? "Overdue - Please remit immediately"
      : "Pending - Due by 21st of following month";
    
    doc.text(statusText, margin, yPos);
    yPos += 8;
  } else {
    // Calculate deadline
    let deadlineYear = year;
    let deadlineMonth = month + 1;
    if (deadlineMonth > 12) {
      deadlineMonth = 1;
      deadlineYear += 1;
    }
    const deadline = new Date(deadlineYear, deadlineMonth - 1, 21);
    
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("Remittance Deadline", margin, yPos);
    yPos += 6;

    doc.setFont("helvetica", "normal");
    doc.text(`Due by: ${formatDate(deadline)}`, margin, yPos);
    yPos += 8;
  }

  // WHT Records Detail Section
  if (whtRecords.length > 0) {
    // Check if we need a new page
    if (yPos > pageHeight - 60) {
      doc.addPage();
      yPos = margin;
    }

    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    doc.text("WHT Deduction Details", margin, yPos);
    yPos += 8;

    // Table header
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    const tableColWidths = [35, 50, 35, 30, 30];
    const tableColXPositions = [
      margin,
      margin + 35,
      margin + 85,
      margin + 120,
      margin + 150,
    ];

    doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
    doc.text("Payee", tableColXPositions[0] + 2, yPos);
    doc.text("Payment", tableColXPositions[1] + 2, yPos);
    doc.text("WHT Type", tableColXPositions[2] + 2, yPos);
    doc.text("Rate", tableColXPositions[3] + 2, yPos);
    doc.text("WHT Amt", tableColXPositions[4] + 2, yPos);
    yPos += 6;

    // Table rows
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    for (const record of whtRecords) {
      // Check if we need a new page
      if (yPos > pageHeight - 25) {
        doc.addPage();
        yPos = margin;
        // Redraw header
        doc.setFontSize(8);
        doc.setFont("helvetica", "bold");
        doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
        doc.text("Payee", tableColXPositions[0] + 2, yPos);
        doc.text("Payment", tableColXPositions[1] + 2, yPos);
        doc.text("WHT Type", tableColXPositions[2] + 2, yPos);
        doc.text("Rate", tableColXPositions[3] + 2, yPos);
        doc.text("WHT Amt", tableColXPositions[4] + 2, yPos);
        yPos += 6;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7);
      }

      doc.rect(margin, yPos - 4, pageWidth - 2 * margin, 5, "S");
      
      // Payee name (truncate if too long, handle null/undefined)
      const payeeName = (record.payeeName || "Unknown").length > 20 
        ? (record.payeeName || "Unknown").substring(0, 17) + "..." 
        : (record.payeeName || "Unknown");
      doc.text(payeeName, tableColXPositions[0] + 2, yPos);
      
      // Payment amount (handle null/undefined)
      doc.text(formatCurrency(record.paymentAmount ?? 0), tableColXPositions[1] + 2, yPos);
      
      // WHT Type (abbreviate, handle null/undefined)
      const whtType = (record.whtType ?? "Unknown").replace(/_/g, " ").substring(0, 25);
      doc.text(whtType, tableColXPositions[2] + 2, yPos);
      
      // Rate (handle null/undefined)
      doc.text(`${record.whtRate ?? 0}%`, tableColXPositions[3] + 2, yPos);
      
      // WHT Amount (handle null/undefined)
      doc.text(formatCurrency(record.whtAmount ?? 0), tableColXPositions[4] + 2, yPos);
      
      yPos += 5;
    }
  }

  // Add important notes
  yPos += 5;
  if (yPos > pageHeight - 40) {
    doc.addPage();
    yPos = margin;
  }

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  doc.text("Important Notes", margin, yPos);
  yPos += 6;

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
  
  const notes = [
    "WHT must be remitted within 21 days of deduction (by 21st of following month)",
    "Late remittances attract 10% per annum penalty + interest + possible imprisonment",
    "WHT serves as advance payment and can be used as tax credit against PIT or CIT",
    "Keep all source documents (invoices, receipts) for NRS (Nigeria Revenue Service) audit purposes",
    "Verify current rates and requirements at www.nrs.gov.ng",
  ];

  for (const note of notes) {
    if (yPos > pageHeight - 25) {
      doc.addPage();
      yPos = margin;
    }
    const noteLines = doc.splitTextToSize(`• ${note}`, pageWidth - 2 * margin - 10);
    doc.text(noteLines, margin + 5, yPos);
    yPos += noteLines.length * 4;
  }

  // Add disclaimer footer
  if (yPos > pageHeight - 25) {
    doc.addPage();
  }
  addDisclaimerFooter(doc, pageWidth, pageHeight);

  const pdfOutput = doc.output("arraybuffer");
  return Buffer.from(pdfOutput);
}

/**
 * Generate PIT Return PDF for individual accounts
 * Reference: NRS (Nigeria Revenue Service) Personal Income Tax Act (PITA) - https://www.nrs.gov.ng/
 * 
 * PIT Filing Deadline: March 31 of the year following the tax year
 * 
 * CRITICAL: This application only supports tax laws valid from 2026 onward per Nigeria Tax Act 2025.
 * NRS was rebranded to NRS (Nigeria Revenue Service) effective January 1, 2026.
 */
export async function generatePITReturnPDF(
  accountId: Types.ObjectId,
  taxYear: number,
  isWatermarked: boolean = false
): Promise<Buffer> {
  // Get user information
  const { default: User } = await import("../user/entity");
  const user = await User.findById(accountId).lean();
  if (!user) {
    throw new Error("User not found");
  }

  // Get PIT summary
  const { pitService } = await import("../pit/service");
  const summary = await pitService.getPITSummary(accountId, taxYear);
  
  // Get PIT remittances
  const remittances = await pitService.getPITRemittances(accountId, taxYear);

  // Get income sources
  const { incomeService } = await import("../income/service");
  const incomes = await incomeService.getIncomesByAccount(accountId.toString(), AccountType.Individual);

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;

  // Header
  let yPos = margin;
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
  doc.text("PERSONAL INCOME TAX (PIT) RETURN", pageWidth / 2, yPos, { align: "center" });
  yPos += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
  doc.text(`Tax Year: ${taxYear}`, pageWidth / 2, yPos, { align: "center" });
  yPos += 6;

  // Taxpayer Information
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  doc.text("Taxpayer Information", margin, yPos);
  yPos += 8;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Name: ${user.firstName || ""} ${user.lastName || ""}`, margin, yPos);
  yPos += 5;
  if (user.email) {
    doc.text(`Email: ${user.email}`, margin, yPos);
    yPos += 5;
  }
  if (user.phoneNumber) {
    doc.text(`Phone: ${user.phoneNumber}`, margin, yPos);
    yPos += 5;
  }
  yPos += 5;

  // If no summary exists, show a helpful message
  if (!summary) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("PIT Return Summary", margin, yPos);
    yPos += 15;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
    const message = `No PIT data found for tax year ${taxYear}.`;
    const messageLines = doc.splitTextToSize(message, pageWidth - 2 * margin);
    doc.text(messageLines, margin, yPos);
    yPos += 10;

    doc.setFontSize(9);
    const instruction = "Add your income sources and expenses to calculate your PIT liability. The system will automatically calculate your PIT based on NRS (Nigeria Revenue Service) regulations effective 2026+.";
    const instructionLines = doc.splitTextToSize(instruction, pageWidth - 2 * margin);
    doc.text(instructionLines, margin, yPos);
    yPos += 15;

    // Add disclaimer footer
    addDisclaimerFooter(doc, pageWidth, pageHeight);

    const pdfOutput = doc.output("arraybuffer");
    return Buffer.from(pdfOutput);
  }

  // PIT Return Summary - Clear Step-by-Step Breakdown
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  doc.text("PIT Return Summary", margin, yPos);
  yPos += 6;

  // Explanation section
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
  const explanation = "This shows how your tax is calculated: Start with your income, subtract deductions and expenses, then calculate tax on what's left.";
  const explanationLines = doc.splitTextToSize(explanation, pageWidth - 2 * margin);
  doc.text(explanationLines, margin, yPos);
  yPos += explanationLines.length * 4 + 6;

  // Summary Table with clear sections
  const colWidths = [120, 60];
  const colXPositions = [margin, pageWidth - margin - 60];

  // ============================================================================
  // SECTION 1: YOUR INCOME
  // ============================================================================
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  doc.text("1. Your Total Income", margin, yPos);
  yPos += 6;

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 8, "S");
  doc.text("Description", margin + 5, yPos);
  doc.text("Amount (NGN)", colXPositions[1], yPos);
  yPos += 8;

  doc.setFont("helvetica", "normal");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Total Gross Income (All money you earned)", margin + 5, yPos);
  doc.text(formatCurrency(summary.totalGrossIncome || 0), colXPositions[1], yPos);
  yPos += 8;

  // ============================================================================
  // SECTION 2: DEDUCTIONS (What reduces your taxable income)
  // ============================================================================
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("2. Deductions (These reduce the amount you pay tax on)", margin, yPos);
  yPos += 6;

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 8, "S");
  doc.text("Description", margin + 5, yPos);
  doc.text("Amount (NGN)", colXPositions[1], yPos);
  yPos += 8;

  doc.setFont("helvetica", "normal");
  
  // Statutory deductions
  if ((summary.totalCRA || 0) > 0) {
    doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
    doc.text("CRA (Consolidated Relief Allowance)", margin + 5, yPos);
    doc.text(formatCurrency(summary.totalCRA || 0), colXPositions[1], yPos);
    yPos += 6;
  }

  if ((summary.totalPension || 0) > 0) {
    doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
    doc.text("Pension Contributions", margin + 5, yPos);
    doc.text(formatCurrency(summary.totalPension || 0), colXPositions[1], yPos);
    yPos += 6;
  }

  if ((summary.totalNHF || 0) > 0) {
    doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
    doc.text("NHF (National Housing Fund)", margin + 5, yPos);
    doc.text(formatCurrency(summary.totalNHF || 0), colXPositions[1], yPos);
    yPos += 6;
  }

  if ((summary.totalNHIS || 0) > 0) {
    doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
    doc.text("NHIS (National Health Insurance)", margin + 5, yPos);
    doc.text(formatCurrency(summary.totalNHIS || 0), colXPositions[1], yPos);
    yPos += 6;
  }

  // New Allowable Deductions (2026+)
  if ((summary.totalHousingLoanInterest || 0) > 0) {
    doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
    doc.text("Housing Loan Interest", margin + 5, yPos);
    doc.text(formatCurrency(summary.totalHousingLoanInterest || 0), colXPositions[1], yPos);
    yPos += 6;
  }

  if ((summary.totalLifeInsurance || 0) > 0) {
    doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
    doc.text("Life Insurance Premium", margin + 5, yPos);
    doc.text(formatCurrency(summary.totalLifeInsurance || 0), colXPositions[1], yPos);
    yPos += 6;
  }

  if ((summary.totalRentRelief || 0) > 0) {
    doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
    doc.text("Rent Relief (20% of rent paid, capped at NGN 500,000)", margin + 5, yPos);
    doc.text(formatCurrency(summary.totalRentRelief || 0), colXPositions[1], yPos);
    yPos += 6;
  }

  // Tax-Deductible Expenses (THE KEY SECTION THE USER ASKED ABOUT)
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.setFont("helvetica", "bold");
  doc.text("Tax-Deductible Company Expenses", margin + 5, yPos);
  doc.setFont("helvetica", "normal");
  doc.text(formatCurrency(summary.totalAllowableDeductions || 0), colXPositions[1], yPos);
  yPos += 6;

  // Add note about tax-deductible expenses
  doc.setFontSize(7);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
  const expenseNote = "Note: Only expenses marked as 'tax-deductible' are included here. These expenses reduce the amount you pay tax on.";
  const expenseNoteLines = doc.splitTextToSize(expenseNote, pageWidth - 2 * margin - 10);
  doc.text(expenseNoteLines, margin + 5, yPos);
  yPos += expenseNoteLines.length * 3 + 4;

  // Total Deductions
  const totalDeductions = (summary.totalCRA || 0) + 
                         (summary.totalPension || 0) + 
                         (summary.totalNHF || 0) + 
                         (summary.totalNHIS || 0) + 
                         (summary.totalHousingLoanInterest || 0) +
                         (summary.totalLifeInsurance || 0) +
                         (summary.totalRentRelief || 0) +
                         (summary.totalAllowableDeductions || 0);
  
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Total Deductions", margin + 5, yPos);
  doc.text(formatCurrency(totalDeductions), colXPositions[1], yPos);
  yPos += 8;

  // ============================================================================
  // SECTION 3: TAXABLE INCOME (After deductions)
  // ============================================================================
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("3. Your Taxable Income (Income minus deductions)", margin, yPos);
  yPos += 6;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Total Gross Income", margin + 5, yPos);
  doc.text(formatCurrency(summary.totalGrossIncome || 0), colXPositions[1], yPos);
  yPos += 6;

  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Less: Total Deductions", margin + 5, yPos);
  doc.setTextColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
  doc.text(`-${formatCurrency(totalDeductions)}`, colXPositions[1], yPos);
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  yPos += 6;

  doc.setFont("helvetica", "bold");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Taxable Income", margin + 5, yPos);
  doc.text(formatCurrency(summary.totalTaxableIncome || 0), colXPositions[1], yPos);
  yPos += 8;

  // Annual Exemption (if applicable)
  if ((summary.annualExemption || 0) > 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(`Annual Exemption (${taxYear >= 2026 ? "NGN 800,000" : "None"})`, margin + 5, yPos);
    doc.text(formatCurrency(summary.annualExemption || 0), colXPositions[1], yPos);
    yPos += 6;
  }
  yPos += 5;

  // ============================================================================
  // SECTION 4: TAX CALCULATION
  // ============================================================================
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("4. Tax Calculation", margin, yPos);
  yPos += 6;

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 8, "S");
  doc.text("Description", margin + 5, yPos);
  doc.text("Amount (NGN)", colXPositions[1], yPos);
  yPos += 8;

  doc.setFont("helvetica", "normal");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("PIT Before WHT Credits", margin + 5, yPos);
  doc.text(formatCurrency(summary.pitBeforeWHT || 0), colXPositions[1], yPos);
  yPos += 6;

  if (summary.whtCredits > 0) {
    doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
    doc.text("Less: WHT Credits Applied (Tax already paid)", margin + 5, yPos);
    doc.setTextColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
    doc.text(`-${formatCurrency(summary.whtCredits || 0)}`, colXPositions[1], yPos);
    doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    yPos += 6;
  }

  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.primaryDark[0], COLORS.primaryDark[1], COLORS.primaryDark[2]);
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("Final PIT Liability (Amount you need to pay)", margin + 5, yPos);
  doc.text(formatCurrency(summary.pitAfterWHT || 0), colXPositions[1], yPos);
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  yPos += 8;

  // ============================================================================
  // SECTION 5: PAYMENT STATUS
  // ============================================================================
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("5. Payment Status", margin, yPos);
  yPos += 6;

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 8, "S");
  doc.text("Description", margin + 5, yPos);
  doc.text("Amount (NGN)", colXPositions[1], yPos);
  yPos += 8;

  doc.setFont("helvetica", "normal");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("PIT Remitted (Tax you have already paid)", margin + 5, yPos);
  doc.setTextColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
  doc.text(formatCurrency(summary.pitRemitted || 0), colXPositions[1], yPos);
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  yPos += 6;

  doc.setFont("helvetica", "bold");
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 6, "S");
  doc.text("PIT Pending (Tax you still need to pay)", margin + 5, yPos);
  if ((summary.pitPending || 0) > 0) {
    doc.setTextColor(COLORS.warning[0], COLORS.warning[1], COLORS.warning[2]);
  } else {
    doc.setTextColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
  }
  doc.text(formatCurrency(summary.pitPending || 0), colXPositions[1], yPos);
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  yPos += 10;

  // Filing Status
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("Filing Status", margin, yPos);
  yPos += 6;

  doc.setFont("helvetica", "normal");
  const filingDeadline = new Date(summary.filingDeadline);
  const statusText = summary.filingStatus === FilingStatus.Filed
    ? `Filed - Deadline: ${formatDate(filingDeadline)}`
    : summary.filingStatus === FilingStatus.Overdue
    ? `Overdue - Deadline: ${formatDate(filingDeadline)} (Please file immediately)`
    : `Not Filed - Deadline: ${formatDate(filingDeadline)}`;
  
  doc.text(statusText, margin, yPos);
  yPos += 8;

  // Income Sources Section
  if (incomes.length > 0) {
    if (yPos > pageHeight - 40) {
      doc.addPage();
      yPos = margin;
    }

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Income Sources", margin, yPos);
    yPos += 6;

    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.rect(margin, yPos - 4, pageWidth - 2 * margin, 6, "S");
    doc.text("Tax Year", margin + 5, yPos);
    doc.text("Month", margin + 50, yPos);
    doc.text("Annual Income (NGN)", margin + 80, yPos);
    yPos += 6;

    doc.setFont("helvetica", "normal");
    for (const income of incomes.filter((i) => i.taxYear === taxYear)) {
      if (yPos > pageHeight - 20) {
        doc.addPage();
        yPos = margin;
      }
      doc.rect(margin, yPos - 4, pageWidth - 2 * margin, 5, "S");
      doc.text(taxYear.toString(), margin + 5, yPos);
      doc.text(income.month ? income.month.toString() : "All", margin + 50, yPos);
      doc.text(formatCurrency(income.annualIncome || 0), margin + 80, yPos);
      yPos += 5;
    }
    yPos += 5;
  }

  // Remittances Section
  if (remittances.length > 0) {
    if (yPos > pageHeight - 40) {
      doc.addPage();
      yPos = margin;
    }

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("PIT Remittances", margin, yPos);
    yPos += 6;

    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.rect(margin, yPos - 4, pageWidth - 2 * margin, 6, "S");
    doc.text("Date", margin + 5, yPos);
    doc.text("Amount (NGN)", margin + 50, yPos);
    doc.text("Reference", margin + 100, yPos);
    yPos += 6;

    doc.setFont("helvetica", "normal");
    for (const remittance of remittances) {
      if (yPos > pageHeight - 20) {
        doc.addPage();
        yPos = margin;
      }
      doc.rect(margin, yPos - 4, pageWidth - 2 * margin, 5, "S");
      doc.text(formatDate(remittance.remittanceDate), margin + 5, yPos);
      doc.text(formatCurrency(remittance.remittanceAmount || 0), margin + 50, yPos);
      doc.text(remittance.remittanceReference || "N/A", margin + 100, yPos);
      yPos += 5;
    }
    yPos += 5;
  }

  // Important Notes
  if (yPos > pageHeight - 50) {
    doc.addPage();
    yPos = margin;
  }

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("Important Notes:", margin, yPos);
  yPos += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  const notes = [
    "This PIT return is based on available data in the system.",
    "You must verify all figures with your accounting records.",
    "PIT filing deadline: March 31 of the year following the tax year.",
    "Late filing may result in penalties and interest charges.",
    "WHT credits can offset your PIT liability per NRS (Nigeria Revenue Service) regulations.",
    "Consult a qualified tax advisor for complex tax situations.",
    "For current NRS (Nigeria Revenue Service) regulations, visit: www.nrs.gov.ng",
  ];

  for (const note of notes) {
    if (yPos > pageHeight - 25) {
      doc.addPage();
      yPos = margin;
    }
    const noteLines = doc.splitTextToSize(`• ${note}`, pageWidth - 2 * margin - 10);
    doc.text(noteLines, margin + 5, yPos);
    yPos += noteLines.length * 4;
  }

  // Add disclaimer footer
  if (yPos > pageHeight - 25) {
    doc.addPage();
  }
  addDisclaimerFooter(doc, pageWidth, pageHeight);

  // Add watermark if required
  if (isWatermarked) {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        addWatermark(doc, pageWidth, pageHeight, "taxcomply.ng");
    }
  }

  const pdfOutput = doc.output("arraybuffer");
  return Buffer.from(pdfOutput);
}

